---
- name: Disable all WIFI.
  hosts: myservers
  become: true
  gather_facts: false

  tasks:
    - name: Shut down hosts
      ansible.builtin.systemd_service:
        name: wpa_supplicant
        state: stopped
        enabled: false
        