---
- name: killall
  hosts: myservers
  gather_facts: false
  tasks:
    - name: killAll
      shell: |
        killall -9 qjackctl
        killall -9 jacktrip
        killall -9 sclang
        killall -9 scsynth
        killall -9 aj-snapshot
        killall -9 jackd
      register: ps
      async: 2592000
      poll: 0

