---
- name: Start fully connected Jacktrip Mesh
  hosts: myservers
  gather_facts: false

  tasks:

    - name: "Connect JackTrip ins"
      shell: jack_connect SuperCollider:out_1 {{item}}:send_1 
      loop: "{{ groups['myservers'] }}"
      loop_control:
        index_var: index
      when: "{{index != groups['myservers'].index(inventory_hostname)}}"

    - name: "Connect SC outs"
      shell: jack_connect SuperCollider:out_1 system:playback_1
      loop: "{{ groups['myservers'] }}"
      loop_control:
        index_var: index
      when: "{{index != groups['myservers'].index(inventory_hostname)}}"
        
    - name: "Connect JackTrip more"
      shell: jack_connect {{item}}:receive_1 SuperCollider:in_2
      loop: "{{ groups['myservers'] }}"
      loop_control:
        index_var: index
      when: "{{index != groups['myservers'].index(inventory_hostname)}}"
 

  vars:
    base_port: 4464