---
- name: mesh
  hosts: myservers
  gather_facts: false
  tasks:
    - name: killAll
      shell: |
        killall -9 qjackctl
        killall jacktrip
        killall sclang
        killall scsynth
        killall aj-snapshot  
        killall jackd
      register: ps
      async: 2592000
      poll: 0

    - name: start jackd
      shell: |
        jackd -P 95 -a a -d alsa -d hw:Gen -r 48000 -p 128 -n 2  &
        sleep 3
      register: ps
      async: 2592000
      poll: 0

    - name: start jacktrip
      shell: |
        jacktrip -S &
        sleep 3
      register: ps
      async: 2592000
      poll: 0
    
    - name: Launch Clients
      shell: jacktrip -n 1 -C {{ hostvars[groups['myservers'][index]].ansible_host }} -J {{ hostvars[groups['myservers'][index]].inventory_hostname}} -K {{ inventory_hostname }} -B {{ base_port + index }}
      async: 2592000
      poll: 0
      loop: "{{groups['myservers']}}"
      loop_control:
        index_var: index
      when: 
        - ansible_host != hostvars[groups['myservers'][index]].ansible_host 
          # ansible_host.split('.')[-1] | int < (hostvars[groups['myservers'][index]].ansible_host).split('.')[-1] | int
    

              
    - name: Launch Clients
      debug:
        msg: | 
          jacktrip -n 1 -C {{ hostvars[groups['myservers'][index]].ansible_host }} -J {{ hostvars[groups['myservers'][index]].inventory_hostname}} -K {{ inventory_hostname }} -B {{ base_port + index }}
         #{{ansible_host}} is trying to connect to {{ hostvars[groups['myservers'][index]].ansible_host }}
      
        #{{groups['myservers'][index]}}
         #{{ ansible_host.split('.')[-1] | int }} {{ (hostvars[groups['myservers'][index]].ansible_host).split('.')[-1] | int }}
          
      loop: "{{groups['myservers']}}"
      loop_control:
        index_var: index
      when: 
        - ansible_host != hostvars[groups['myservers'][index]].ansible_host 
        - ansible_host.split('.')[-1] | int < (hostvars[groups['myservers'][index]].ansible_host).split('.')[-1] | int
      #"{{ ansible_play_hosts | difference([inventory_hostname]) }}"


  
    
  vars:
    base_port: 4464
