---
- name: mesh
  hosts: myservers
  gather_facts: false
  tasks:
    - name: killAll
      shell: |
        killall -9 qjackctl
        killall -9 jacktrip
        killall -9 sclang
        killall -9 scsynth
        killall -9 aj-snapshot  
        killall -9 jackd
      register: ps
      async: 2592000
      poll: 0

    - name: start jackd
      shell: |
        jackd -P 95 -a a -d alsa -d hw:Gen -r 48000 -p 128 -n 2  &
        sleep 3
      register: ps
      async: 2592000
      poll: 0

    - name: start jacktrip
      shell: |
        jacktrip -S &
        sleep 3
      register: ps
      async: 2592000
      poll: 0
    

    
  vars:
    base_port: 4464
