---
- name: Start fully connected Jacktrip Mesh
  hosts: myservers
  gather_facts: false

  tasks:

    - name: "Connect Physical inputs"
      shell: |
        jack_connect system:capture_1 SuperCollider:in_1
        jack_connect system:capture_2 SuperCollider:in_1

#        jack_connect system:capture_1 SuperCollider:in_{{groups['myservers'].index(inventory_hostname) +1}}
#        jack_connect system:capture_2 SuperCollider:in_{{groups['myservers'].index(inventory_hostname) +1}}

    - name: "Connect JackTrip ins"
      shell: jack_connect SuperCollider:out_{{index+1}} {{item}}:send_1 
      loop: "{{ groups['myservers'] }}"
      loop_control:
        index_var: index
      when: "{{index != groups['myservers'].index(inventory_hostname)}}"

    - name: "Connect JackTrip outs"
      shell: jack_connect {{item}}:receive_1 system:playback_1
      loop: "{{ groups['myservers'] }}"
      loop_control:
        index_var: index
      when: "{{index != groups['myservers'].index(inventory_hostname)}}"
        
 

  vars:
    base_port: 4464