# Launch SuperCollider stuff
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/student/remote/
      state: directory
      owner: student
      group: student
      mode: '0755'
    async: 2592000
    poll: 0

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: spectralfx.scd
      dest: /home/student/remote/spectralfx.scd
      owner: student
      group: student
      mode: '0644'

  - name: run sc script
    shell: |
      export DISPLAY=:0.0
      sclang /home/student/remote/spectralfx.scd
    async: 2592000
    poll: 0
